### 添加乘客信息
POST {{GATEWAY}}/member/passenger/save
Content-Type: application/json
token: {{token}}

{
  "name": "wj4",
  "idCard": 123456789,
  "type": 3
}

### 查询乘客
GET {{GATEWAY}}/member/passenger/query-list?page=1&size=2
Accept: application/json
token: {{token}}




###