server:
  port: 8000
spring:
  application:
    name: gateway
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedMethods: "*"
            allowedHeaders: "*"
            allowedOriginPatterns: "*"
            allowCredentials: true
      routes:
        - id: member
          uri: http://localhost:8001
          predicates:
            - Path=/member/**
        - id: business
          uri: http://localhost:8002
          predicates:
            - Path=/business/**
        - id: batch
          uri: http://localhost:8003
          predicates:
            - Path=/batch/**