server:
  port: 8000
spring:
  application:
    name: gateway
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedMethods: "*"
            allowedHeaders: "*"
            allowedOriginPatterns: "*"
            allowCredentials: true
      routes:
        - id: member
          uri: lb://member
          predicates:
            - Path=/member/**
        - id: business
          uri: lb://business
          predicates:
            - Path=/business/**
        - id: batch
          uri: lb://batch
          predicates:
            - Path=/batch/**