server:
  port: 8002
  servlet:
    context-path: /business
spring:
  application:
    name: business
  data:
    redis:
      host: 1.15.145.217
      password: "010622"
      database: 1
      port: 6379
      lettuce:
        pool:
          max-active: 10
          max-idle: 10
          min-idle: 1
          time-between-eviction-runs: 10
  cloud:
    openfeign: #feign.sentinel.enabled改为true后不加会报错
      lazy-attributes-resolution: true
    sentinel:
      transport: #启用sentinel控制台
        port: 8719
        dashboard: localhost:18080
      datasource:
        flow: # 这个可以随意
          nacos:
            server-addr: localhost:8848
            namespace: train
            group-id: DEFAULT_GROUP
            data-id: sentinel-flow
            rule-type: flow #限流
        degrade: # 这个可以随意
          nacos:
            server-addr: localhost:8848
            namespace: train
            group-id: DEFAULT_GROUP
            data-id: sentinel-degrade
            rule-type: degrade #熔断
  # 数据库连接
  datasource:
    url: jdbc:mysql://localhost:3307/train_business?characterEncoding=UTF8&autoReconnect=true&serverTimezone=Asia/Shanghai
    username: root
    password: "010622wj"
    driver-class-name: com.mysql.cj.jdbc.Driver
  main:
    allow-circular-references: true
logging:
  level:
    com.wj.train.business.mapper: trace

mybatis:
  mapper-locations: classpath:/mapper/**/*.xml
feign:
  sentinel:
    enabled: true #sentinel默认不监控feign

