server:
  port: 8002
  servlet:
    context-path: /business
spring:
  application:
    name: business
  # 数据库连接
  datasource:
    url: jdbc:mysql://localhost:3307/train_business?characterEncoding=UTF8&autoReconnect=true&serverTimezone=Asia/Shanghai
    username: root
    password: "010622wj"
    driver-class-name: com.mysql.cj.jdbc.Driver
logging:
  level:
    com.wj.train.business.mapper: trace

mybatis:
  mapper-locations: classpath:/mapper/**/*.xml