server:
  port: 8003
  servlet:
    context-path: /batch
spring:
  application:
    name: batch
  # 数据库连接
  datasource:
    url: jdbc:mysql://localhost:3307/train_batch?characterEncoding=UTF8&autoReconnect=true&serverTimezone=Asia/Shanghai
    username: root
    password: "010622wj"
    driver-class-name: com.mysql.cj.jdbc.Driver
logging:
  level:
    com.wj.train.batch.mapper: trace

mybatis:
  mapper-locations: classpath:/mapper/**/*.xml
